### ISSUE TITLE
Failed to start containers due to error starting browser

### ISSUE THREAD

**Issue by shelane** [docksal/drupal7-advanced#16]
I was unable to get the environment running with `fin init` due to this error:
```
ERROR: for d7a_browser_1  Cannot start service browser: driver failed programming external connectivity on endpoint d7a_browser_1 (9a442f810e25db3eb4
ERROR: for browser  Cannot start service browser: driver failed programming external connectivity on endpoint d7a_browser_1 (9a442f810e25db3eb4ac1e8ffb2331f7d52d55d6a7d32830d2f6fc18f03b6463): Error starting userland proxy: Bind for 0.0.0.0:5900 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.
```

**Comment by lmakarov** [comment]
Looks like you have another project already running using the `5900` port (VNC port).

According to our [docs on Behat](https://docs.docksal.io/en/master/tools/behat/), the following should go into the `docksal.yml`:

```
# Browser
browser:
  hostname: browser
  image: selenium/standalone-chrome
  dns:
    - ${DOCKSAL_DNS1}
    - ${DOCKSAL_DNS2}
```

What's there [now](https://github.com/docksal/drupal7-advanced/blob/62521511d72dd5d9892c97fa9eb67ec998011666/.docksal/docksal.yml#L70-L78):

```
  # Browser
  browser:
    hostname: browser
    image: selenium/standalone-chrome-debug
    ports:
      - "5900:5900"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}
```

assumes using Behat with the debug/VNC mode enabled. You can only have one project like that, define a different host port (e.g. `"5901:5900"`) or make it dynamic altogether (e.g. `"5900"`).

We should just go with the default configuration with no VNC out-of-the-box.

**Comment by achekulaev** [comment]
Fixed in https://github.com/docksal/drupal7-advanced/pull/15/files#diff-c0f8c94528e80a375d7251349f012f53
