### ISSUE TITLE
How to run the (node 4) forever with some parameter when 'fin' starts?

### ISSUE THREAD

**Issue by ArtuGit** [docksal/drupal7-advanced#2]
I have created the new custom command 'init' that installs node v4.8.2 and `forever` and then starts `forever`.
But it works only inside this command (even I run this bash script directly in `fin bash`)! Other sessions do not see node 4 and `forever`. it works only if I type all commands into a terminal, one by one.
How to setup node v4.8.2 by default and run `forever` which is available for all `fin bash` sessions (And hence for my application).

**Comment by ArtuGit** [comment]
My problem is that web app. and other `fin bash` sessions do not see a process (`forever`) which has been run by the `init` script.

**Comment by achekulaev** [comment]
Sorry I don't fully understand this part:
```
Other sessions do not see node 4 and forever
```
What "other sessions" do you mean?

**Comment by ArtuGit** [comment]
`fin bash` sessions

**Comment by achekulaev** [comment]
I have hard time reproducing it. `node` is already installed in `docksal/cli:1.2-php7` so I was not re-installing `node` and I had only installed `forever` with `npm install forever -g`.

Then I created a simple `app.js`:
```js
let i=0
require('timers').setInterval(
	function () {
		console.log("Working " + ++i + "...")
	}, 
	1000);
```

Then I ran it in one session (the black window on the background) and checked if it's visible from another sessions (the white window on the foreground). It was visible. 

Screenshot:

<img width="1419" alt="demo docker cli var www docker fin bash 202x38 2017-05-02 11-10-34" src="https://cloud.githubusercontent.com/assets/402007/25624692/365c97c2-2f28-11e7-9adb-43b8d96d6b15.png">

Then I created a custom Docksal command `forever`

```bash
#!/bin/bash

APP_NAME="app.js"

if [[ "$1" == "start" ]]; then
	fin exec forever start "$APP_NAME"
elif [[ "$1" == "stop" ]]; then
	fin exec 'forever stop $(forever list | grep "'$APP_NAME'" | sed -e "s/\s\{1,\}/ /g" | cut -d " " -f 7)'
elif [[ "$1" == "list" ]]; then
	fin exec forever list
else
	echo "Usage 'fin forever list|start|stop'"
fi
```

And used it to start my app with forever. And it works.

Screenshot:

<img width="1417" alt="2222" src="https://cloud.githubusercontent.com/assets/402007/25625531/bcaf8d14-2f2a-11e7-83a5-66de55b8d58c.png">

How do I replicate your issue? Do I need to install specific node version? Can it be a node version + forever issue?

**Comment by achekulaev** [comment]
Update: I hope you're not trying to find your installed `node` and `forever` in **another** project. Because each project is encapsulated in it's own environment. `cli` container is **not** shared between projects. Whatever you install in one project stays in that project (just like the Vegas thing).

**Comment by ArtuGit** [comment]
@achekulaev You did a big work to reproduce this issue. Thank you a lot.

It easy to reproduce to be relevant for my case. At first, I would like to remind you that I should do it for node 4. It is a key point.

I have command `init` (.docksal/commands/init):
```
#!/bin/bash
fin run-cli bash -i .docksal/scripts/commands/init.sh
```
I have `init.sh`  (.docksal/scripts/commands/init.sh)
```
#!/bin/bash
nvm install v4.8.2
nvm use v4.8.2
npm install forever -g

cd /var/www/drupal-nodejs
forever start app.js nodejs.config.docksal.js
```
`fin init` works properly.

![image](https://cloud.githubusercontent.com/assets/10816446/25632609/f3488978-2f7c-11e7-8616-04bc2fd0f5e5.png)

But another `fin bash` session (and the webapp. accordingly) does not see node 4 and `forever` for node 4.
![image](https://cloud.githubusercontent.com/assets/10816446/25632918/1320bd3c-2f7e-11e7-9c18-547cc43fa10f.png)

(It sees `forever` for node 6 which was installed too. But I need `forever` for node 4).

Why Do I by such way? Because by another way it impossible to run `nvm` with the correct result. Each next `fin exec` command does not see that node should be v4.  A new command always started from node v6.
But my way is wrong too, by similar reason with node version.

So I suppose, there is a problem with `nvm` which is invoked from bash scripts. If I do it manually (typing of commands), it works.

A solution might be node v4 by default. When I run `forever` without `nvm` for node v6, other sessions see `forever list` correctly. 

How to setup node v4.8.2 by default?
Or maybe you have an idea to run 'nvm' correctly?

**Comment by lmakarov** [comment]
@ArtuGit Use `fin exec` instead of `fin run-cli`.

```
exec <command|file>      	Execute a command or a script in cli
run-cli (rc) <command>   	Run a command in a standalone cli container in the current directory
``` 

`run-cli` starts a completely standalone `docksal/cli` containers, which disappears once it finishes doing what you asked it to do. Any changes done inside that container are gone at that point (unless the output was written to the mounted volume (`/var/www`)).

**Comment by ArtuGit** [comment]
Wow!

Now It works! Thank you.))

```
#!/bin/bash
fin exec bash -i .docksal/scripts/commands/init.sh
```

P.S.
I tried `fin exec` but it did not work. Probably, there were some other differences, e.g. `bash` without `-i`, that is important for `nvm`.

**Comment by achekulaev** [comment]
@lmakarov looks like `run-cli` might be a confusing name for running ad-hoc standalone container.

@ArtuGit nvm use does not modify version permanently. It modifies in in bash session, temporary.
You need init like this

```bash
#!/bin/bash

cd "$PROJECT_ROOT"
# Install 4.8.2
fin exec nvm install v4.8.2

# Install forever for 4.8.2
fin exec "nvm use v4.8.2 && npm install forever -g"

# Run
cd drupal-nodejs
fin exec "nvm use v4.8.2 && forever start app.js nodejs.config.docksal.js"
```

**Comment by ArtuGit** [comment]
@achekulaev It works too, 
but when I tried this way without `cd "$PROJECT_ROOT"` it did not work.
ok. Now I know.

**Comment by ArtuGit** [comment]
It does not work again. 

I have this `init` command:

```
#!/bin/bash

## Start 'drupal-nodejs' app and other.

fin exec sudo chmod -R 777 /home/docker/.drush/cache

fin exec "cd /var/www/html && drush cc all"

cd "$PROJECT_ROOT"

# Install 4.8.2
fin exec nvm install v4.8.2

# Install forever for 4.8.2
fin exec "nvm use v4.8.2 && npm install forever -g"

# Run drupal-nodejs
cd drupal-nodejs
fin exec "nvm use v4.8.2 && forever start app.js nodejs.config.docksal.js"
```
This comand works correctly, it starts the node app using `forever` in node v.4

But, when I run `forever` in other `fin bash` session it does not see `forever` and has node v6 as the default version.
![image](https://cloud.githubusercontent.com/assets/10816446/25695441/da5574b8-30bb-11e7-8823-6e572f839b45.png)

What is the trick? It worked a couple days ago. I tried to reinstall Docksal (`fin remove` and `fin start`) but with no result.

**Comment by ArtuGit** [comment]
It works. Sorry for the noise.
I should do  `nvm use v4.8.2` to see 'forever' in node v4.

But this task still has to be handled in manual mode because `cli` IP is changed each time then 'fin' starts.https://github.com/docksal/docksal/issues/195
