### ISSUE TITLE
What handles the URL rewrite rules (Apache or Nginx)?

### ISSUE THREAD

**Issue by ArtuGit** [docksal/drupal7-advanced#3]
What handles the URL rewrite rules (Apache or Nginx)?
I use https://www.drupal.org/project/js module.

Standard rewrite rules for this module (in .htaccess) do not work for some reason.
```
  # Rewrite JavaScript callback URLs of the form js.php?q=x.
  RewriteCond %{REQUEST_URI} ^\/([a-z]{2}\/)?js\/.*
  RewriteRule ^(.*)$ js.php?q=$1 [L,QSA]
  RewriteCond %{QUERY_STRING} (^|&)q=((\/)?[a-z]{2})?(\/)?js\/.*
  RewriteRule .* js.php [L]
```
Why? Can rewrite rules be handled by Nginx?
If yes, is there Nginx configuration to set such rules for Nginx?
https://www.drupal.org/node/886446

**Comment by achekulaev** [comment]
Rewrite rules in `.htaccess` files are handled by `web` container that uses `docksal/web:1.0-apache2.2` so yes they are handled by Apache. And they are definitely working because otherwise software like Drupal would not work at all, as it relies heavily on `.htaccess` redirects.

So I would suppose either Apache never reaches your rules because there is another rewrite rule that precedes your rules in `.htaccess` and stops other rules processing before it even reaches your rules. Or your rules do not match URLs you try.

**Comment by ArtuGit** [comment]
There was an issue with Apache default settings in this configuration.
There is the solution which I have found on d.org:

> It seems Apache automatically calls js.php for requests like /js/*. This happens because of MultiViews option that is enabled by default. You should add this line to your `.htaccess` in order to disable the multiviews feature and make requests work properly:
> `Options -MultiViews`
>

**Comment by lmakarov** [comment]
@ArtuGit thanks for figuring this out. I updated our apache settings in the web container.
We will be doing more refactoring of the web container image and release all that at some point this month.

**Comment by lmakarov** [comment]
@ArtuGit I pushed updates to the web images.

Can you please test your setup with the following versions and report back?

```
docksal/web:edge-apache2.2
docksal/web:edge-apache2.4
```

**Comment by ArtuGit** [comment]
Currently, I have `image: docksal/web:1.0-apache2.2` in `web` in `docksal.yml`.

How can I update the Apache image? 
Change a line in `docksal.yml` and `fin up` ?

**Comment by lmakarov** [comment]
> Change a line in docksal.yml and fin up ?

Yes. Depending on what type on configuration you use (default stacks vs custom) you edit the container images either in `docksal.env` or `docksal.yml`. In your case it's going to be in `docksal.yml`.

**Comment by ArtuGit** [comment]
The both images work without `Options -MultiViews` in local `.htaccess`.
That's correct, I think.

@lmakarov @achekulaev 
Please explain what is the difference among `docksal/web:1.0-apache2.2 ` and `docksal/web:edge-apache2.2` . 

P.S.
It is incredibly how it works.
And it is quite stable! ))
I will learn docker, and it is an awesome start point.
I hope it is transparent and I can add my own docker container into Docksal.

**Comment by lmakarov** [comment]
@ArtuGit edge tag is built from the develop branch, while the 1.0 one is the latest stable release.

Here's the relevant configuration change I made to get `MultiViews` out of the way by default:
https://github.com/docksal/service-web/compare/v1.0.0...develop#diff-d90757fadcce0ee46dfb98ca8bb6bc52R16
