### ISSUE TITLE
cli (Node.js server host) IP address is changing

### ISSUE THREAD

**Issue by ArtuGit** [docksal/drupal7-advanced#4]
Now it is 172.19.0.3.

![image](https://cloud.githubusercontent.com/assets/10816446/25653055/e2324148-2ff3-11e7-87ec-d2ad8a366715.png)

Yesterday it was 172.19.0.4.

Despite `cli` as a synonym for IP works in node app.js configuration code, I can not set `cli` as a Node.js server host in the Node.js module Dashboard (this configuration is stored in a DB).

![image](https://cloud.githubusercontent.com/assets/10816446/25653129/33b4be38-2ff4-11e7-96d1-0be4d8571af5.png)

Possible solutions:
1. Set a static digital synonym for `cli`.
2. Somehow get or parse the dynamic `cli` IP. We can set an received IP using `drush vset --exact nodejs_server_host '172.19.0.3'`

Could you advise?

**Comment by achekulaev** [comment]
You can just use `cli` as Node.js server host value

**Comment by ArtuGit** [comment]
https://github.com/docksal/docksal/issues/195
