### ISSUE TITLE
site_install_anothersite doesn't work, anothersite URL is not correct

### ISSUE THREAD

**Issue by ilakic** [docksal/drupal7-advanced#7]
init script doesn't install "anothersite" because of an error in line 125. You need to remove underscore (__site_install_anothersite_ => _site_install_anothersite_). 

After that fix, "anothersite" is installed but URL from terminal ( http://anothersite.drupal7.docksal ) is not correct - result is "_Page not found_" (with reaper 404 picture). Maybe the problem for this lies in docksal.env?

**Comment by ilakic** [comment]
> After that fix, "anothersite" is installed but URL from terminal ( http://anothersite.drupal7.docksal ) is not correct - result is "Page not found" (with reaper 404 picture). Maybe the problem for this lies in docksal.env?

Are there any progress about this issue?

**Comment by lmakarov** [comment]
Try now. I pushed a bunch of fixes.

**Comment by ilakic** [comment]
It works now! Tnx!

**Comment by ilakic** [comment]
One more question - in this init script you haven't defined variable _SOURCE_ALIAS_ (or I did something wrong)? Because I get `Error: no alias record could be found for source`. That happens when I try to import database.

**Comment by achekulaev** [comment]
@ilakic I'd recommend opening a new issue if there is another unrelated issue
