### ISSUE TITLE
Import database, SOURCE_ALIAS variable isn't defined?

### ISSUE THREAD

**Issue by ilakic** [docksal/drupal7-advanced#8]
In this init script there isn't defined variable _SOURCE_ALIAS_ (or I did something wrong)? Because I get an error: `Error: no alias record could be found for source`. That happens when I try to import database (I just want to test that import option).

**Comment by lmakarov** [comment]
Right, the variable goes into `docksal.env`. I added an example there. Thanks for reporting!
